formatter: "markdown" # this is required

version: ""

recursive:
  enabled: false
  path: .

sections:
  hide: []
  show: []

  hide-all: false # deprecated in v0.13.0, removed in v0.15.0
  show-all: true  # deprecated in v0.13.0, removed in v0.15.0

content: ""

output:
  file: "README.md"
  mode: replace
  template: |-
    # terraform-module-opswatch-metric-stream
    This module creates a CloudWatch Metrics Stream with a HTTPS endpoint as target. This is primarily designed for OpsWatch.
    # TF Module Documentation
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->    

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true