formatter: "markdown" # this is required

version: ""

recursive:
  enabled: false
  path: .

sections:
  hide: []
  show: []

  hide-all: false # deprecated in v0.13.0, removed in v0.15.0
  show-all: true  # deprecated in v0.13.0, removed in v0.15.0

content: ""

output:
  file: "README.md"
  mode: replace
  template: |-
    # terraform-module-vpc
    This module creates a workload VPC. It can be configured with either its own NAT or as a spoke VPC in the central TGW design. This requires both an existing deployment of the tgw-central module once, and a call to vpc-tgw-attachment for each of these VPCs.

    The VPCs CIDR is a variable. If you want to combine it with FNT ordered CIDRs, this module won't do that, but you can provide so by the variable. Per default, unique CIDRs aren't assumed.
    # TF Module Documentation
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->    

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true